FROM jekyll/jekyll:4.2.0@sha256:1ead0631cb82fdbd5950a5eb5b4bfbec5e6e97bb234afc058072e3f32e537751
# Image to use M1 Macs
# FROM younglook/jekyll-arm64:latest

# install imagemagick
RUN apk update && apk add imagemagick