FROM jekyll/jekyll:3.8.5@sha256:266d5974688c8d1ccd921fa1f2eac44684b6b515ab54915c25a28f2fff73d222
# Image to use M1 Macs
# FROM younglook/jekyll-arm64:latest

# install imagemagick
RUN apk update && apk add imagemagick