FROM jekyll/jekyll:3.8.6@sha256:9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34
# Image to use M1 Macs
# FROM younglook/jekyll-arm64:latest

# install imagemagick
RUN apk update && apk add imagemagick