source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sass-converter', '~> 2.0'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'rake'
gem 'rake-jekyll'
gem 'jekyll-feed'
gem 'mini_magick'
gem 'blur_image'