welcome_at_ordina:
  title: Welcome @ Ordina
  description: Learn how Ordina is organized and get to know each other.
  category: soft skills
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [anja_van_acker]
security_awareness:
  title: Security Awareness
  category: security
  trajectory: kickstarter
  organizing_unit: security
git_best_practices:
  title: Git best practices
  description: Good knowledge of Git is invaluable. One of the biggest advantages of Git is its branching capabilities. We'll teach you the best practices for working with Git.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [yannick_de_turck]
dev_environment:
  title: The dev environment
  description: You'll learn about your typical development environment. Topics include Git, Maven, IntelliJ, ...
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [kevin_van_den_abeele]
essentials_communicatie:
  title: Communication essentials
  category: soft skills
  trajectory: kickstarter
  organizing_unit: external
java_8_9_10:
  title: Java 8/9/10 Language Features
  description: Each new Java version includes new and improved features to enhance our day-to-day programming. It is important to stay up-to-date in order to achieve maximum efficiency as a Java developer.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [yannick_de_turck]
unit_testing:
  title: Java Unit Testing & Mocking + TDD
  description: Writing good unit tests to test the behaviour of your code is a core skill of any developer nowadays. A new functionality should always come together with a series of unit tests. At the same time, writing good and clear unit tests helps you to document what your functionality is doing exactly.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [maarten_casteels]
spring:
  title: Spring
  description: The Spring Framework is the most popular Java framework and should be well-known by all Java developers. It offers many projects to help you build up your architecture and when trying to come up with a solution for a specific use case such as batch processing, security and data access.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [ken_coenen]
docker:
  title: Docker
  category: containerization
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [tom_verelst]
clean_code:
  title: Clean code
  description: Writing clean code is what separates good developers from average developers. If you aren't paying attention to how you structure and wire your code, it can rapidly become a burden to maintain and comprehend what a piece of code is doing exactly.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [pieter_van_hees]
html_css_javascript:
  title: HTML5, CSS3, JavaScript
  description: This session will cover the new things in the HTML5 spec (elements, API's), the possibilities with CSS3 and how to write structured CSS with Sass.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [yannick_vergeylen]
agile_scrum:
  title: Agile & Scrum introduction
  category: methodology
  trajectory: kickstarter
  organizing_unit: external
frontend_build_tools:
  title: Frontend build tools, testing, package managers etc
  description: The number of possible tools for testing and packaging a frontend application have grown significantly over the last few years. When finished with these courses, you won't be overwhelmed anymore and you'll know which tool to use for your newest project.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [michael_vervloet]
typescript:
  title: TypeScript
  description: TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. It allows us to use new features of the ES-spec (classes, interfaces, …), adds strong typing and adds Typings for autocompletion. It will also speed up development and you will write less error prone code.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [kevin_van_houtte]
introduction_angular:
  title: Introduction Angular + ngCLI
  description: Angular has been around some time at Ordina. It is the preferred MV* framework within JWorks. We will look into Angular (v2+) and will give you some tips and tricks on how to build a performance-driven enterprise application.
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [ryan_de_gruyter]
devops_ci_cd:
  title: DevOps + CI/CD
  category: methodology
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [tim_vierbergen]
ddd_microservices:
  title: Introduction to DDD & Microservices
  category: architecture
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [tim_ysewyn, kevin_van_houtte]
kubernetes:
  title: Kubernetes
  category: cloud
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [tom_verelst]
introduction_cloud:
  title: Introduction to Cloud (cloud providers + cloud platforms)
  description: Platform as a service is a category of cloud computing services that allow customers to develop, run, and manage applications without the complexity of building and maintaining the infrastructure.
  category: cloud
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [dieter_hubau, bas_moorkens]
brand_yourself:
  title: Brand yourself
  category: soft skills
  trajectory: kickstarter
  organizing_unit: external
security_principles:
  title: Security Principles
  description: We believe that every Ordina consultant should have security in his or her DNA. During this course, you'll learn to identify possible security risks as early as possible in a development process.
  category: security
  trajectory: kickstarter
  organizing_unit: jworks
  teacher: [tim_de_grande]
dev_case:
  title: Dev case
  category: development
  trajectory: kickstarter
  organizing_unit: jworks
management_meets_kickstarters:
  title: Management meets kickstarters
  category: soft skills
  trajectory: kickstarter
graduation_day:
  title: Graduation day
  category: soft skills
  trajectory: kickstarter
preferred_stack:
  title: Introduction JWorks Technology Radar & preferred stack
  description: You'll get acquainted with the technologies we love and put into practise in our greenfield projects. During the day, we discuss the technologies on our tech radar and update them if necessary.
  category: methodology
  trajectory: accelerator
  organizing_unit: jworks
advanced_spring:
  title: Spring recap & advanced
  description: Over the years, the Spring framework by Pivotal has become the de facto standard in developing Java applications. We'll deep-dive into the different projects of this large ecosystem.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [ken_coenen, yannick_de_turck]
spring_security:
  title: Spring Security deep-dive
  description: In nearly every project, you have to deal with security. We have a thorough look at the Spring Security framework.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [ken_coenen, tim_de_grande]
databases:
  title: Database modeling and database comparison
  description: During this session, we'll go over the basics of database modeling. You'll also learn what database types exist and which type to use when implementing a certain use case.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [chris_de_bruyne, tom_van_den_bulck]
clean_architecture:
  title: Clean architecture
  description: Software architecture is getting a lot of attention. It looks beyond the details of today’s technologies to the underlying trends, techniques, and principles that underpin lasting success in our fast-moving field. It is critical to today’s business success; yet it requires technical, business and organizational talents and skills that warrant their own path of career development, education, and research.
  category: architecture
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [pieter_van_hees]
advanced_security:
  title: Advanced Security Principles
  description: We believe that every Ordina consultant should have security in his or her DNA. During this course, we'll discuss security at the infrastructure-, database-, server- and application level. You'll learn to identify possible security risks as early as possible in a development process.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tim_de_grande, ken_coenen]
angular_with_typescript:
  title: Angular with TypeScript
  description: TypeScript ensures maintainable software... if it is well used. You'll learn to write TypeScript and Angular, our standard choice when building slick frontend applications.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [ryan_de_gruyter, orjan_de_smet, ivar_van_hartingsveldt, frederic_ghijselinck]
progressive_web_apps:
  title: Progressive Web Apps
  description: Learn how to write web applications that offer the user functionality such as working offline, push notifications, and device hardware access traditionally available only to native mobile applications.
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [steve_de_zitter, jan_de_wilde, ryan_de_gruyter, orjan_de_smet, ivar_van_hartingsveldt, frederic_ghijselinck]
project_estimations:
  title: Pragmatic Project Estimations
  description: Estimating projects is very difficult and not an exact science. However, there are some tips and tricks which can help you estimating an upcoming project. You'll be an expert in breaking up a large project into smaller pieces, identifying risks and estimating the unexpected.
  category: project management
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [ken_coenen]
team_leadership:
  title: Team leadership
  description: Which styles of leadership are acceptable in which situation? What sort of leader are you? How to coach and when? How to handle difficult situations? In this three-day course you'll discover answers to these questions.
  category: soft skills
  trajectory: accelerator
  organizing_unit: jworks
insights_discovery:
  title: Insights Discovery
  category: soft skills
  trajectory: accelerator
  organizing_unit: external
storytation:
  title: Storytation
  description: It is inevitable. Everyone has to give a presentation someday. But what makes a presentation stick with your audience? You will discover what characteristics an intriguing story must have, that you need to know your audience and how you can tell the story with great confidence.
  category: soft skills
  trajectory: accelerator
  organizing_unit: external
ddd_cqrs_event_sourcing:
  title: Domain-Driven Design, CQRS and Event Sourcing
  description: We believe in microservices. Microservices and DDD principles are thick as thieves. You'll learn about bounded contexts, event sourcing and the frameworks you can use to implement these principles.
  category: architecture
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [yannick_de_turck, pieter_van_hees, jeff_mesens]
microservices_architectures:
  title: Microservice architecture design
  description: Distributed systems and microservices are a hot topic these days. It's all about developing smaller applications that work together. It's all about the operational measures that need to be taken into account when putting a distributed system into production. It's all about faster business value delivery. This in-depth course is an A-Z journey through the microservices landscape.
  category: architecture
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tim_ysewyn, kevin_van_houtte]
cdct:
  title: Consumer-Driven Contract Testing
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tim_ysewyn]
spring_cloud:
  title: Spring Cloud overview
  category: development
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tim_ysewyn]
advanced_docker:
  title: Advanced Docker
  description: Packing your application into a container makes your application highly portable. Containerization is an indispensible facet when talking about deploying your application anywhere, on any platform. We'll put theory into practise by looking at Docker.
  category: containerization
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tom_verelst]
advanced_kubernetes:
  title: Advanced Kubernetes
  category: containerization
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [tom_verelst, bas_moorkens]
openshift:
  title: Advanced Openshift
  description: The "cloud"... another buzzword. But investigating Platform as a Service can be of great value to your organization. Building and maintaining server racks in your basement is not always necessary anymore. You have different levels of abstracting the infrastructure side of things. You'll lears about the basic principles of cloud native applications and PaaS platforms and we'll dig deeper into OpenShift.
  category: containerization
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [dieter_hubau, bas_moorkens]
ansible:
  title: Automatic provisioning with Ansible
  category: containerization
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [dieter_hubau, jan_van_der_veken]
projects_lessons_learned:
  title: JWorks projects - lessons learned & best practices
  description: Alright, cool! You have been granted a project by a customer and the development team can start in a couple of weeks! But there are a lot of things to think about when scoring and managing a project, eg. presales activities, scope management, team coaching, architecture, backlog prioritization, etc. This course is about all of those topics and is essential in becoming a good team leader or project manager.
  category: methodology
  trajectory: accelerator
  organizing_unit: jworks
  teacher: [ken_coenen]