name: Build Jekyll site

on:
  pull_request:
    branches:
      - source
  workflow_dispatch:

permissions:
  contents: read


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.153.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll
        run: bundle exec jekyll build
