name: Build Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251 # v1.150.0
        with:
          ruby-version: 3
          bundler-cache: true

      - uses: ordina-jworks/jekyll-action@1c99c679098cc977d53907b30218f1ad10815f8a # v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true
          pre_build_commands: |
            apk --update add imagemagick musl
