name: 'Validate Renovate config'

on:
  push:
    branches: [ "source" ]
    paths:
      - 'renovate.json'
  pull_request:
    branches: [ "source" ]
    paths:
      - 'renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: 'Validate Renovate config'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '18'

      - name: Validate Renovate config
        run: npx --package renovate -c renovate-config-validator
