name: 'Validate Renovate config'

on:
  push:
    branches: [ "source" ]
    paths:
      - 'renovate.json'
  pull_request:
    branches: [ "source" ]
    paths:
      - 'renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: 'Validate Renovate config'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'

      - name: Validate Renovate config
        run: npx --package renovate -c renovate-config-validator
